import type { Metadata } from 'next';
import { Analytics } from '@vercel/analytics/react';
import { Noto_Sans } from 'next/font/google';
import './globals.css';
import Sidebar from '@/components/sidebar';
import Header from '@/components/header';

const notoSans = Noto_Sans({
  variable: '--font-noto-sans',
  weight: ['400', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <Analytics />
      <body className={notoSans.className}>
        <div className='flex h-screen bg-[#F6F8FA]'>
          <Sidebar />
          <div className='flex w-full flex-col p-4'>
            <Header />
            <main className='mt-4 h-full rounded-xl bg-white'>{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
